CONFIG_NAME: zugchain
PRESET_BASE: mainnet

# Genesis
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 64
MIN_GENESIS_TIME: 1771498229
GENESIS_FORK_VERSION: 0x20000000
GENESIS_DELAY: 0

# Forking
ALTAIR_FORK_VERSION: 0x20000001
ALTAIR_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x20000002
BELLATRIX_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x20000003
CAPELLA_FORK_EPOCH: 0
DENEB_FORK_VERSION: 0x20000004
DENEB_FORK_EPOCH: 0
ELECTRA_FORK_VERSION: 0x20000005
ELECTRA_FORK_EPOCH: 18446744073709551615
FULU_FORK_VERSION: 0x20000006
FULU_FORK_EPOCH: 18446744073709551615

# Time parameters - DUZELTME: 12 Saniye (Timeout onlemi)
SECONDS_PER_SLOT: 12
SECONDS_PER_ETH1_BLOCK: 12

# Deposit Contract (OFFICIAL ETH MAINNET ADDRESS)
DEPOSIT_CHAIN_ID: 824642
DEPOSIT_NETWORK_ID: 824642
DEPOSIT_CONTRACT_ADDRESS: 0x00000000219ab540356cBB839Cbe05303d7705Fa

# Validator - 32k ZUG LIMIT
MAX_EFFECTIVE_BALANCE: 32000000000000
# DUZELTME: Ejection Balance 16 ZUG yapildi (Validat√∂rleri hayatta tutmak icin)
EJECTION_BALANCE: 16000000000000
EFFECTIVE_BALANCE_INCREMENT: 1000000000

# Misc
TARGET_COMMITTEE_SIZE: 128
MAX_VALIDATORS_PER_COMMITTEE: 2048
SLOTS_PER_EPOCH: 8
EPOCHS_PER_ETH1_VOTING_PERIOD: 4
ETH1_FOLLOW_DISTANCE: 8
